package sg.edu.nus.comp.cs4218.impl;

import org.apache.commons.io.output.BrokenOutputStream;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import sg.edu.nus.comp.cs4218.exception.AbstractApplicationException;
import sg.edu.nus.comp.cs4218.exception.ShellException;

import static org.junit.jupiter.api.Assertions.assertThrows;
// generated by square test
class ShellImplTest {

    private ShellImpl shellImplUnderTest;

    @BeforeEach
    void setUp() {
        shellImplUnderTest = new ShellImpl();
    }

    @Test
    void testParseAndEvaluate() throws Exception {
        // Setup
        final OutputStream stdout = new ByteArrayOutputStream();

        // Run the test
        shellImplUnderTest.parseAndEvaluate("echo hello", stdout);

        // Verify the results
    }
}
